name: "Fetch RSS"
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rss_link: ["https://buttondown.email/denonews/rss", "https://deno.com/feed"]
    steps:
      - name: "[SETUP] Checkout Bot"
        uses: actions/checkout@v3
        with:
          ref: bot
      - name: "[SETUP] Deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: "[SETUP] Dep Cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}
      - name: "[Fetch] RSS Feed"
        env:
          BOT_ID: ${{ secrets.BOT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          RSS_LINK: ${{ matrix.rss_link }}
        run: |
          deno run -A --unstable https://raw.githubusercontent.com/${{ github.repository }}/dev/main.ts
      - name: "[WRAPUP] Write Last Published Time"
        run: |
          git config user.name "Deno RSS Bot"
          git config user.email "deno-rss@example.com"

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add *.json
          git commit -m "${{ matrix.rss_link }} last_published updated" --allow-empty
          git push


