name: "Fetch RSS"
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: "[SETUP] Checkout"
        uses: actions/checkout@v3
        with:
          ref: bot
      - name: "[SETUP] Deno"
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: "[SETUP] Dep Cache"
        uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deps.ts') }}
      - name: "[Fetch] RSS Feed"
        env:
          BOT_ID: ${{ secrets.BOT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          RSS_LINK: "https://buttondown.email/denonews/rss"
        run: |
          deno task run
      - name: "[WRAPUP] Write Current Time"
        run: |
          git config user.name "Deno RSS Bot"
          git config user.email "deno-rss@example.com"

          date --utc --iso-8601=seconds > last_published.txt

          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add last_published.txt
          git commit -m "bot:last_published.txt updated"
          git push


